<a href="https://colab.research.google.com/github/JasClaren/GCI-World-April-2026/blob/main/lec2_notebook_answer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2 Practice and Comprehensive Questions Solutions

In [1]:
import numpy as np
import numpy.random as random
import numpy.linalg as LA

# Display up to 3 decimal places
%precision 3

'%.3f'

### <Practice Question 2-1>

(1) Create two 1-dimensional `np.ndarray` arrays with your favorite values as elements, and use the `type()` function to confirm that they are of type `np.ndarray`.

In [2]:
# (1)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

(2) Perform arithmetic operations on the two 1-dimensional arrays created in (1).

In [3]:
type(array1)

numpy.ndarray

In [4]:
type(array2)

numpy.ndarray

In [5]:
# (2)
print('Addition', array1 + array2)
print('Substraction', array1 - array2)
print('Multiplication', array1 * array2)
print('Division', array1 / array2)

Addition [ 7  9 11 13 15]
Substraction [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.167 0.286 0.375 0.444 0.5  ]


(3) Create a function that takes a 1-dimensional array as input and outputs a 1-dimensional array where the input is normalized.

Here, normalization of a vector (using the L2 norm) means scaling the original vector so that the square root of the sum of the squares of all its elements equals 1.

In this task, please implement the function using only **Numpy's universal operations and functions**.


In [6]:
def normalize(a):
    return a / np.sqrt(np.sum(a**2))

In [7]:
array1

array([1, 2, 3, 4, 5])

In [8]:
print(normalize(array1))
print(np.sqrt(np.sum(normalize(array1)**2)))

[0.135 0.27  0.405 0.539 0.674]
1.0


### <Practice Question 2-2>

(1) For any array you create, retrieve and display the first value from the front and the first value from the back.

In [9]:
a = np.array([1, 2, 3, 4, 5])
print("The first value from the front:", a[0])
print("The second value from the back:", a[-1])

The first value from the front: 1
The second value from the back: 5


(2)  Implement a function that takes a one-dimensional Numpy array with integer values as an argument and outputs an array containing elements that are either odd (leave a remainder of 1 when divided by 2) or leave a remainder of 2 when divided by 4.

In [10]:
def make_bool_ids(a):
    idx1 = (a % 2 != 0)
    idx2 = (a % 4 == 2)
    idx = idx1 | idx2
    return a[idx]

In [11]:
# Input Example
a = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])
print(make_bool_ids(a))
# Output Example
# np.array([1, 1, 2, 2, 3, 3, 5, 5])

[1 1 2 2 3 3 5 5]


(3)  Implement a function that takes a positive integer as an argument and counts the number of perfect squares less than the given number using boolean indexing. (Hint: List enough perfect squares in ascending order and count those smaller than the argument.)

In [12]:
def count_square(n):
    array = np.arange(1, n) ** 2
    answer = np.sum((array < n))
    return answer

In [13]:
# Alternative Solution
def count_square(n):
    array = np.arange(1, n)
    answer = np.sum((array < np.sqrt(n)))
    return answer

In [14]:
# Input Example
n = 20
answer = count_square(n)
print(answer)
# Output Example
# The positive perfect squares less than 20 are 1, 4, 9, and 16.
# 4

4


### <Practice Question 2-3>

(1) Store the test results for 5 students over 4 test sessions in a 2-dimensional array, with 100 points as the maximum score. Here, axis 0 corresponds to the students, and axis 1 corresponds to the test sessions. The values can be arbitrary.

In [15]:
array = np.array([
    [90, 100, 80, 56],
    [67, 94, 29, 90],
    [94, 56, 92, 74],
    [39, 46, 62, 74],
    [23, 48, 81, 83]
])

(2) For each student, calculate the highest score, lowest score, average, and variance across the 4 test sessions. Store the results in a 2-dimensional array where axis 0 corresponds to the students and axis 1 corresponds to the aggregation results (highest score, lowest score, average, variance).

In [16]:
print('student1',
    f'Highest Score: {np.max(array, axis=1)[0]}',
    f'Lowest Score: {np.min(array, axis=1)[0]}',
    f'Average Score: {np.mean(array, axis=1)[0]}',
    f'Variance: {np.var(array, axis=1)[0]}'
)

print('student2',
    f'Highest Score: {np.max(array, axis=1)[1]}',
    f'Lowest Score: {np.min(array, axis=1)[1]}',
    f'Average Score: {np.mean(array, axis=1)[1]}',
    f'Variance: {np.var(array, axis=1)[1]}'
)

print('student3',
    f'Highest Score: {np.max(array, axis=1)[2]}',
    f'Lowest Score: {np.min(array, axis=1)[2]}',
    f'Average Score: {np.mean(array, axis=1)[2]}',
    f'Variance: {np.var(array, axis=1)[2]}'
)

print('student4',
    f'Highest Score: {np.max(array, axis=1)[3]}',
    f'Lowest Score: {np.min(array, axis=1)[3]}',
    f'Average Score: {np.mean(array, axis=1)[3]}',
    f'Variance: {np.var(array, axis=1)[3]}'
)

print('student5',
    f'Highest Score:{np.max(array, axis=1)[4]}',
    f'Lowest Score:{np.min(array, axis=1)[4]}',
    f'Average Score:{np.mean(array, axis=1)[4]}',
    f'Variance:{np.var(array, axis=1)[4]}'
)

array2 = np.array([
    [np.max(array, axis=1)[0], np.min(array, axis=1)[0], np.mean(array, axis=1)[0], np.var(array, axis=1)[0]],
    [np.max(array, axis=1)[1], np.min(array, axis=1)[1], np.mean(array, axis=1)[1], np.var(array, axis=1)[1]],
    [np.max(array, axis=1)[2], np.min(array, axis=1)[2], np.mean(array, axis=1)[2], np.var(array, axis=1)[2]],
    [np.max(array, axis=1)[3], np.min(array, axis=1)[3], np.mean(array, axis=1)[3], np.var(array, axis=1)[3]],
    [np.max(array, axis=1)[4], np.min(array, axis=1)[4], np.mean(array, axis=1)[4], np.var(array, axis=1)[4]],
])

student1 Highest Score: 100 Lowest Score: 56 Average Score: 81.5 Variance: 266.75
student2 Highest Score: 94 Lowest Score: 29 Average Score: 70.0 Variance: 666.5
student3 Highest Score: 94 Lowest Score: 56 Average Score: 79.0 Variance: 237.0
student4 Highest Score: 74 Lowest Score: 39 Average Score: 55.25 Variance: 186.6875
student5 Highest Score:83 Lowest Score:23 Average Score:58.75 Variance:619.1875


In [17]:
array2

array([[100.   ,  56.   ,  81.5  , 266.75 ],
       [ 94.   ,  29.   ,  70.   , 666.5  ],
       [ 94.   ,  56.   ,  79.   , 237.   ],
       [ 74.   ,  39.   ,  55.25 , 186.688],
       [ 83.   ,  23.   ,  58.75 , 619.188]])

In [18]:
array2[:,2].reshape(5,1)

array([[81.5 ],
       [70.  ],
       [79.  ],
       [55.25],
       [58.75]])

(3) For each test score, calculate the absolute difference between the score and the student's average score, resulting in a 2-dimensional array with shape (5, 4).

In [19]:
array3 = np.abs(array - array2[:,2].reshape(5,1))

In [ ]:
print(array3)
print(array3.shape)

[[ 8.5  18.5   1.5  25.5 ]
 [ 3.   24.   41.   20.  ]
 [15.   23.   13.    5.  ]
 [16.25  9.25  6.75 18.75]
 [35.75 10.75 22.25 24.25]]
(5, 4)


### <Practice Question 2-4>

(1) Create a 1-dimensional np.ndarray with 100 consecutive integers from 0 to 99, and reshape it into a 2-dimensional array with shape (10, 10).

In [20]:
array1 = np.arange(0,100).reshape(10,10)
array1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

(2) From the array created in (1), extract the even rows (using 0-based indexing), resulting in a 2-dimensional array with shape (5, 10).

In [21]:
idx1 = np.arange(0, array1.shape[0], 2)
array1[idx1, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

(3) From the array created in (1), extract the odd columns (using 0-based indexing), resulting in a 2-dimensional array with shape (10, 5).

In [22]:
idx2 = np.arange(1, array1.shape[1], 2)
array1[:,idx2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

(4) From the array created in (1), extract the values in even rows and odd columns (using 0-based indexing), resulting in a 2-dimensional array with shape (5, 5).

In [23]:
array1[np.ix_(idx1, idx2)]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

***

## 2.7 Comprehensive Question

**Question 1**\
Recently, in natural language processing using deep learning, models based on Google’s Transformer have gained attention due to their human-level performance on several NLP tasks.

In January 2020, Google introduced [Reformer](https://arxiv.org/abs/2001.04451), which improves the time and space complexity of the Transformer model. In this task, we will implement a part of the Reformer paper, which uses [*cross-polytope LSH*](https://arxiv.org/abs/1509.02897) to improve the time complexity of the Transformer, with guided instructions.

Consider the following question:
>Given $n$ vectors, we want to assign the same integer value to "similar" vectors and different integer values to "dissimilar" vectors. In this context, "similar" vectors are those whose angle is close to 0.


The challenges of this problem are as follows:
- How small should the angle be for vectors to be considered "similar"?
- Even if vectors $a$ and $b$, and  $b$ and $c$ are "similar", $a$ and $c$ may not necessarily be considered "similar."
- To compute the angle $\theta$, we can use their inner product and norms to calculate $\cos \theta$. We could tehn sort htis value and assign integers accordingly, but sorting can become slow as $n$ increases (since the number of combinations of vectors is $_nC_2 = O(n^2)$).

We consider the following probablistic approach:

1. Rotate all vectors by the same random angle.

2. Vectors that are "similar" will, with **high probability**, remain in the same quadrant after rotation, while vectors that are "dissimilar" will, with **high probability**, end up in different quadrants.

3. Therefore, by assigning each vector an integer value corresponding to the quadrant it belongs to after the random rotation, the problem can be solved with **high probability**.

Let's implement this approach.



This time, we consider 100 3D row vectors.

In [24]:
A = random.randn(100, 3) # A matrix stacked with 100 3D row vectors
print(A)

[[ 0.785 -0.697 -0.021]
 [-1.49   0.425  0.409]
 [-0.889 -1.322 -0.191]
 [-0.081 -2.858  0.184]
 [-0.954 -1.207 -0.074]
 [-0.429 -0.355 -0.158]
 [ 1.306  0.778 -0.533]
 [ 1.139 -1.113  0.399]
 [-0.089 -0.614 -0.359]
 [-0.67   0.901  1.339]
 [ 1.078 -0.847 -1.139]
 [ 1.262 -0.645  1.022]
 [ 0.019  1.16  -1.734]
 [-0.266  0.362  1.124]
 [-2.104 -0.762 -1.143]
 [ 1.562 -0.451  2.147]
 [ 0.634  1.229 -0.709]
 [-0.13   0.226  1.564]
 [ 0.475 -1.471  0.147]
 [-1.73  -0.182 -1.944]
 [-0.512 -1.566 -1.487]
 [-0.475 -1.621  0.117]
 [-0.275 -0.96   0.604]
 [ 1.146 -1.176 -1.946]
 [ 0.524 -0.904  0.541]
 [-0.152  0.137 -2.32 ]
 [-0.223 -0.479 -2.032]
 [-0.344 -0.634  0.987]
 [-0.342  0.126  0.326]
 [ 1.075 -2.087 -0.535]
 [ 1.355 -0.298  0.091]
 [ 1.294 -2.395  0.258]
 [ 0.719 -0.199 -0.76 ]
 [ 0.878  0.128 -0.206]
 [-1.026  3.183  1.102]
 [-0.582  0.004  0.081]
 [-0.354  0.633 -1.127]
 [ 0.897 -0.408  0.249]
 [ 1.45   1.169 -1.801]
 [-0.244  0.648  0.792]
 [-0.323 -0.535  0.207]
 [ 0.713  0.581 

(1) Generate a rotation matrix $R$ that rotates 100 vectors, and compute the matrix of rotated vectors stacked vertically into a shape of (100, 3). Here, the 3D rotation matrix $R$ for a random rotation is generated by passing a 1D array of three randomly generated angle parameters to the `gen_R_3d` function.

In [25]:
# (1)
def gen_R_3d(p):
    px, py, pz = p
    Rx = np.array([
        [1, 0, 0],
        [0, np.cos(px), np.sin(px)],
        [0, -np.sin(px), np.cos(px)]
    ])
    Ry = np.array([
        [np.cos(py), 0, -np.sin(py)],
        [0, 1, 0],
        [np.sin(py), 0, np.cos(py)]
    ])
    Rz = np.array([
        [np.cos(pz), np.sin(pz), 0],
        [-np.sin(pz), np.cos(pz), 0],
        [0, 0, 1]
    ])

    return Rz @ Ry @ Rx

p =  2 * np.pi * random.rand(3)
R = gen_R_3d(p)

B = (R @ A.T).T
print(B)

[[-1.025  0.15  -0.171]
 [ 1.354 -0.828 -0.223]
 [-0.443 -1.542 -0.035]
 [-2.025 -1.875 -0.767]
 [-0.293 -1.507 -0.121]
 [-0.017 -0.569  0.106]
 [-0.37   1.446  0.605]
 [-1.478  0.192 -0.688]
 [-0.467 -0.493  0.228]
 [ 1.36   0.186 -1.081]
 [-1.543  0.178  0.874]
 [-1.089  0.642 -1.206]
 [ 0.506  0.602  1.933]
 [ 0.659  0.13  -1.007]
 [ 0.567 -2.195  1.082]
 [-0.919  1.096 -2.282]
 [ 0.362  1.206  0.91 ]
 [ 0.557  0.186 -1.473]
 [-1.365 -0.566 -0.477]
 [ 0.599 -1.611  1.963]
 [-1.12  -1.527  1.158]
 [-0.87  -1.39  -0.422]
 [-0.415 -0.771 -0.772]
 [-1.989 -0.054  1.588]
 [-0.901 -0.13  -0.747]
 [-0.255 -0.237  2.303]
 [-0.609 -0.659  1.898]
 [-0.054 -0.58  -1.075]
 [ 0.378 -0.151 -0.272]
 [-2.341 -0.565  0.027]
 [-1.075  0.851 -0.231]
 [-2.554 -0.523 -0.825]
 [-0.759  0.352  0.659]
 [-0.511  0.733  0.176]
 [ 3.231  1.355 -0.356]
 [ 0.393 -0.435 -0.044]
 [ 0.475  0.034  1.253]
 [-0.83   0.445 -0.38 ]
 [-0.422  1.693  1.916]
 [ 0.792  0.3   -0.624]
 [-0.147 -0.571 -0.294]
 [-0.1    0.884 

(2) To normalize each vector obtained in (1) so that the L2 norm equals 1 and then stack them vertically to form a (100, 3) matrix, you would follow these steps:

Compute the L2 norm for each vector.
Normalize each vector by dividing by its L2 norm.
Stack the normalized vectors without changing their order.

In [26]:
# (2)
B_norm_l2 = LA.norm(B, ord=2, axis=1, keepdims=True)
B_normalized = B / B_norm_l2
print(B_normalized)

[[-0.976  0.143 -0.163]
 [ 0.845 -0.517 -0.139]
 [-0.276 -0.961 -0.022]
 [-0.707 -0.655 -0.268]
 [-0.191 -0.979 -0.079]
 [-0.03  -0.983  0.183]
 [-0.229  0.898  0.375]
 [-0.9    0.117 -0.419]
 [-0.652 -0.688  0.319]
 [ 0.778  0.106 -0.619]
 [-0.866  0.1    0.49 ]
 [-0.624  0.367 -0.69 ]
 [ 0.242  0.288  0.926]
 [ 0.544  0.107 -0.832]
 [ 0.226 -0.874  0.431]
 [-0.341  0.407 -0.847]
 [ 0.233  0.776  0.586]
 [ 0.351  0.117 -0.929]
 [-0.879 -0.365 -0.307]
 [ 0.229 -0.617  0.752]
 [-0.505 -0.688  0.522]
 [-0.514 -0.821 -0.25 ]
 [-0.355 -0.66  -0.662]
 [-0.781 -0.021  0.624]
 [-0.765 -0.111 -0.634]
 [-0.11  -0.102  0.989]
 [-0.29  -0.314  0.904]
 [-0.045 -0.474 -0.879]
 [ 0.772 -0.309 -0.556]
 [-0.972 -0.234  0.011]
 [-0.773  0.612 -0.166]
 [-0.934 -0.191 -0.302]
 [-0.713  0.331  0.619]
 [-0.561  0.805  0.193]
 [ 0.918  0.385 -0.101]
 [ 0.669 -0.739 -0.075]
 [ 0.354  0.025  0.935]
 [-0.817  0.438 -0.374]
 [-0.163  0.653  0.739]
 [ 0.753  0.285 -0.593]
 [-0.223 -0.866 -0.447]
 [-0.101  0.896 

(3) For the 100 vectors with a norm of 1 obtained in (2), compute a matrix of shape (100, 6) by stacking the original 100 vectors and their -1 multiplied counterparts **horizontally**, without changing the order of the vectors.

In [27]:
# (3)
C = np.concatenate([B_normalized, -B_normalized], axis=1)
print(C)

[[-0.976  0.143 -0.163  0.976 -0.143  0.163]
 [ 0.845 -0.517 -0.139 -0.845  0.517  0.139]
 [-0.276 -0.961 -0.022  0.276  0.961  0.022]
 [-0.707 -0.655 -0.268  0.707  0.655  0.268]
 [-0.191 -0.979 -0.079  0.191  0.979  0.079]
 [-0.03  -0.983  0.183  0.03   0.983 -0.183]
 [-0.229  0.898  0.375  0.229 -0.898 -0.375]
 [-0.9    0.117 -0.419  0.9   -0.117  0.419]
 [-0.652 -0.688  0.319  0.652  0.688 -0.319]
 [ 0.778  0.106 -0.619 -0.778 -0.106  0.619]
 [-0.866  0.1    0.49   0.866 -0.1   -0.49 ]
 [-0.624  0.367 -0.69   0.624 -0.367  0.69 ]
 [ 0.242  0.288  0.926 -0.242 -0.288 -0.926]
 [ 0.544  0.107 -0.832 -0.544 -0.107  0.832]
 [ 0.226 -0.874  0.431 -0.226  0.874 -0.431]
 [-0.341  0.407 -0.847  0.341 -0.407  0.847]
 [ 0.233  0.776  0.586 -0.233 -0.776 -0.586]
 [ 0.351  0.117 -0.929 -0.351 -0.117  0.929]
 [-0.879 -0.365 -0.307  0.879  0.365  0.307]
 [ 0.229 -0.617  0.752 -0.229  0.617 -0.752]
 [-0.505 -0.688  0.522  0.505  0.688 -0.522]
 [-0.514 -0.821 -0.25   0.514  0.821  0.25 ]
 [-0.355 -

(4) (Somewhat Difficult)
Currently, in a 3D space, there are 8 quadrants numbered from 0 to 7. Instead of directly finding the quadrant, we will use 6 standard basis vectors and their inverse (6 vectors in total). The task is to find the "most similar" vector from this set.

After rotating the vectors, find the corresponding vector number and store it in a (100, 1) matrix.
(Hint: Think about how to assign the vector number using the normalized vectors. You can avoid using the inner product for efficiency. If you're unsure, try considering the case in 2D and then apply the same idea to 3D. You can utilize the normalization step from part (2).)

In [28]:
# (4)
C_argmax = np.argmax(C, axis=1).reshape(-1,1)
print(C_argmax)

[[3]
 [0]
 [4]
 [3]
 [4]
 [4]
 [1]
 [3]
 [4]
 [0]
 [3]
 [5]
 [2]
 [5]
 [4]
 [5]
 [1]
 [5]
 [3]
 [2]
 [4]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]
 [5]
 [0]
 [3]
 [3]
 [3]
 [3]
 [1]
 [0]
 [4]
 [2]
 [3]
 [2]
 [0]
 [4]
 [1]
 [3]
 [4]
 [5]
 [3]
 [1]
 [1]
 [1]
 [3]
 [5]
 [4]
 [0]
 [3]
 [2]
 [5]
 [0]
 [1]
 [5]
 [4]
 [5]
 [4]
 [5]
 [4]
 [1]
 [4]
 [0]
 [2]
 [0]
 [5]
 [1]
 [3]
 [1]
 [0]
 [1]
 [5]
 [1]
 [1]
 [3]
 [3]
 [2]
 [3]
 [4]
 [2]
 [1]
 [4]
 [2]
 [3]
 [2]
 [2]
 [0]
 [0]
 [5]
 [0]
 [1]
 [4]
 [5]
 [0]
 [4]
 [3]]


The 100 integers obtained here will be the values assigned to 100 vectors.

(5) (For those with extra time)
For the 100 vectors, calculate the cosine of the angle $\theta$ between every pair of vectors. Verify that vectors that are "similar" (i.e., have a small angle between them) are likely to have been assigned the same integer value, while vectors that are "dissimilar" (i.e., have a large angle between them) are likely to have been assigned different integer values.

In [29]:
# (5)
D = B_normalized
D_num = C_argmax

#Setting a threshold for cosine similarity to determine similarity.
threshold = 1 / np.sqrt(2)

n_similar = 0           # Number of similar vectors
n_similar_same = 0      # Number of similar vectors with the same index
n_notsimilar = 0        # Number of dissimilar vectors
n_notsimilar_dif = 0    # Number of dissimilar vectors with different indices
for i in range(100):
    for j in range(i+1,100):
        cos = np.dot(D[i],D[j]) / (LA.norm(D[i]) * LA.norm(D[j]))
        # Similar vectors
        if cos > threshold:
            n_similar += 1
            if D_num[i] == D_num[j]:
                n_similar_same += 1
        # Dissimilr vectors
        else:
            n_notsimilar += 1
            if D_num[i] != D_num[j]:
                n_notsimilar_dif += 1

print('Proportion of similar vectors with the same integer value assigned: ', n_similar_same / n_similar)
print('Proportion of dissimilar vectors with different integer values assigned]: ', n_notsimilar_dif / n_notsimilar)

Proportion of similar vectors with the same integer value assigned:  0.631578947368421
Proportion of dissimilar vectors with different integer values assigned]:  0.9135860607487638
